### ISSUE TITLE
Pattern simulation error

### ISSUE THREAD

**Issue by GTerHaar** [BYU-MicrostructureOfMaterials/OpenXY#8]
Hi,

I am having a problem with the simulation patterns generated. I have not been able to work out where the problem lies. I am assuming that it could either be a microscope settings issue, or calibration issue. (am am assuming the latter). (see simulated pattern below)

![image](https://cloud.githubusercontent.com/assets/14994414/10604498/f7da37be-7724-11e5-8f7c-8af3d9a453c2.png)

I am calibrating the PC from my .tiff images (option).  Since I do not have access to the parallel programming option, I can not calibrate using the points option. (is there a way around this)

My microscope setting I believe are fine?:

![image](https://cloud.githubusercontent.com/assets/14994414/10604626/ea6de8a4-7725-11e5-9634-b00a0c1dc230.png)

Any help on fixing the simulation pattern problem would be appreciated.

Thanks

**Comment by bjack205** [comment]
Your camera elevation is atypical. Camera elevations are typically 10 degrees, but I believe can vary from -10 to 10. The camera elevation is the inclination of the camera normal to the horizontal. 90 degrees would mean the plane of your camera is parallel with the the floor.

**Comment by eretnek** [comment]
The simulated pattern you see that is so terrible is because you have no
pattern center in the .cpr file, so it just picks one for you, and the one
it picks is terrible (I assume because Brian thinks he's hilarious, but
probably so you don't actually use it).  Once you run the tiff calibration,
however, you should be golden, or goldenesque anyway.  My guess is that
your camera elevation is whats causing the problem, as Brian said.

Hopefully we'll change it so it checks the tiff to get your initial guess
so that your simulated pattern looks better.  For now, starting the scan
with the display patterns box checked should show you how close you are.
